### ISSUE TITLE
osrd-ui stylesheets leak outside of osrd-ui components

### ISSUE THREAD

**Issue by emersion** [osrd-project/osrd-ui#988]
Rules like the following are included in our dist CSS files:

```css
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}
```

@RostomBoudi suggested either nesting all rules under osrd-ui specific classes, or disabling [TailwindCSS preflight rules](https://tailwindcss.com/docs/preflight).
